spring.application.name=NUM_Payroll
spring.datasource.url=jdbc:mysql://localhost:3306/payroll_system?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=panha@sql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Thymeleaf configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.jackson.time-zone=Asia/Phnom_Penh
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Phnom_Penh
